apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps 
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 30000
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 60
          periodSeconds: 20
        env:
        - name: MINIKUBE_IP
          value: $(MINIKUBE_IP)
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "my_ip"
spec:
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: 21
    protocol: TCP
    nodePort: 21
    name: 21-ftps
  - port: 30000
    nodePort: 30000
    protocol: TCP
    name: 30000-ftps
  selector:
    app: ftps
